language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t soumik1978/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true soumik1978/docker-react npm run test
